#!/usr/bin/env bash
### this script is just meant to convert a gophermap into something to look at in my terminal
### you can use this as a base to convert the gophermap into any other format you like
IFS=$'\t'
tr -d '\r' | sed 's/^\(.\)/\1\t/g' \
  | while read type desc path domain port;do
      if [ "$type" = "." ];then
        break
      fi
      if [ "$type" = i ];then
        printf "[i] %s\n" "$desc"
      elif [ "$type" = p -o "$type" = g ];then ### things in here are any things to be inlined. not only just images.
        ### need to download the image and inline it with img2sixel
        printf "[p] -----START OF INLINED DATA-----\n"
        gopher "$domain" "$port" "/$type$path" 2>/dev/null
        printf "[p] -----END OF INLINED DATA-----\n"
        ### inside that script it'll notice it is a png, then instead of xli it, it'll img2sixel?
      else
        if grep '^URL:' <<< $path 2>&1 >/dev/null;then
          printf "[%s] %s: %s\n" "$type" "$desc" "$(printf "%s\n" "$path" | cut -d: -f2-)"
        else
          printf "[%s] %s: %s\n" "$type" "$desc" "$(printf "scheme: gopher\ndomain: %s\nport: %s\npath: %s\n" "$domain" "$port" "$type$path" | urijoin)"
        fi
      fi
done
### we don't have a way of knowing what file we're reading... pass as argument instead of stdin? :/
