#!/usr/bin/env bash
if [ "$#" -lt 3 ];then
  printf "usage: domain port path\n"
  exit 1
fi
if [ "$2" = "" ];then
  port=70
else
  port=$2
fi
type="$(printf "%s\n" "$3" | cut -d/ -f2)"
if [ "$type" = "" ];then
  type=1
  path="$3"
else
  path="/$(printf "%s\n" $3 | cut -d/ -f3-)" #keep the leading /
fi

if [ "$type" = 0 ];then
  mimetype=text/plain
fi
if [ "$type" = 1 ];then
  mimetype=text/gophermap
fi
if [ "$type" = p ];then
  mimetype=image/png
fi
if [ "$type" = g ];then
  mimetype=image/gif
fi
if [ "$type" = I ];then
  mimetype=image/unknown
fi
if [ "$type" = 7 ];then
  mimetype=text/gophermap
  path="${path}"$'\t'"$(echo | dmenu -p 'gopher> ')"
fi
if [ "$type" = 9 ];then
  mpv "gopher://$1:$port/$type$path"
fi


mkdir -p "${PREFIX}/var/cache/gopher"

cachename="${PREFIX}/var/cache/gopher/$(printf "gopher://%s:%s/%s\n" "$1" "$port" "$type$path" | tr '\n' '\0' | xargs -0 uriescape | sed 's|/|%2f|g')"

if [ ! -e $cachename ];then #if the cache doesn't exist, make it.
  printf "%s\r\n" "$path" | ncat $1 $port > "$cachename"
fi
#cat "$cachename"
uristart "$(printf "file://%s?mime-type=%s\n" "$cachename" "$mimetype")"
rm "$cachename" #ha. who needs cache?
